config/routes.rb
Rails.application.routes.draw do

  root :to => 'application#index'

  get 'logout' => 'sessions#destroy', :as => 'log_out'
  get 'login' => 'sessions#new', :as => 'log_in'
  post 'login' => 'sessions#create'
  get 'register' => 'users#new', :as => 'sign_up'
  post 'register' => 'users#create'

  get 'user_id' => 'application#user_id'
  get 'current_contact' => 'application#current_contact', :defaults => {format: :json}

  resources :users, :except => :new
  resources :sessions, :except => :new

  scope '/api' do
    resources :contacts, :defaults => {format: :json}

    resources :resource_types
    resources :partners

    resources :event_documents

    resources :events

    resources :finance_programs

    resources :currencies

    resources :finance_sources

    resources :projects, :defaults => {format: :json}

    resources :project_tasks, :defaults => {format: :json}

    resources :project_statuses, :defaults => {format: :json}

    resources :project_task_statuses, :defaults => {format: :json}

    resources :project_resources, :defaults => {format: :json}

    get 'resoursable' => 'resoursable#index', :defaults => {format: :json}

    resources :equips, :defaults => {format: :json}

    resources :equip_statuses, :defaults => {format: :json}

    resources :intellect_types

    resources :intellect_properties

    resources :socnet_links

    resources :socnets

    resources :theses

    resources :papers

    resources :degrees

    resources :ranks

    resources :scientists

    resources :rooms

    resources :subunits

    resources :specialties

    resources :faculties

    resources :universities

    resources :students

    resources :industries

    resources :workposts

    resources :skills, :defaults => {format: :json}

    resources :organizations

    resources :contact_data

    resources :links
  end

  mount RailsAdmin::Engine => '/adminpanel', :as => 'rails_admin'

  get '*path' => 'application#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :contact
  accepts_nested_attributes_for :contact

  def name
    self.email
  end

  attr_accessor :password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create, :message => "can't be blank"
  validates_presence_of :email, :message => "can't be blank"
  validates_uniqueness_of :email, :message => "already in use"

  before_create :encrypt_password

  # Password and auth stuff.
  def saved_password
    @saved_password ||= BCrypt::Password.new(encrypted_password)
  end

  def saved_password=(new_password)
    @saved_password = BCrypt::Password.create(new_password)
    self.encrypted_password = @saved_password
  end

  def encrypt_password
    self.saved_password = password if password.present?
  end

  def self.authenticate email, password
    user = where(:email => email.downcase).first
    if user && user.saved_password == password
      user
    else
      nil
    end
  end
end

app/controllers/users_controller.rb
class UsersController < InheritsController
  def new
    @user = User.new
  end

  def create
    user_params[:email].downcase!

    existing_user = User.find_by_email user_params[:email]
    if existing_user
      flash.alert = 'Пользователь с таким email уже существует'
      render 'new'
      return
    end

    if user_params[:password] != user_params[:password_confirmation]
      flash.alert = 'Пароли не совпадают'
      render 'new'
      return
    end

    @user = User.new(user_params)
    if @user.save!
      @user.contact = Contact.new({name:@user.email})
      @user.contact.contact_data = ContactDatum.create({email:@user.email})
      session[:user_id] = @user.id
      redirect_to root_url, :notice => 'Добро пожаловать!'
    else
      flash.alert = 'Произошла ошибка сервера, вы не зарегистрированы :('
      render 'new'
    end
  end
  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :salt, :encrypted_password)
      #params.require(:user).permit(:email, :password_hash, :password_salt)
    end

end

app/views/users/_new.html.slim
h1 Зарегистрироваться
= form_for :user, url: register_path do |f|
  - if @user && @user.errors.any?
    .error_messages
      h2
        | Ошибка заполнения формы
      ul
        - for message in @user.errors.full_messages
          li
            = message
  - if flash[:alert]
    .alert.alert-warning.alert-dismissible.fade.in role="alert"
      button.close.pull-right type="button" data-dismiss="alert" aria-label="Close"
        span aria-hidden="true"
          | ×
      h4
        | Ошибка регистрации
      p
        = flash[:alert]
  .form-group.col-md-12
    .col-md-4.col-lg-3.text-right
      = f.label :email
    .col-md-6.col-lg-7
      = f.email_field :email, :class => 'form-control', :required => true

  .form-group.col-md-12
    .col-md-4.col-lg-3.text-right
      = f.label :password
    .col-md-6.col-lg-7
      = f.password_field :password, :class => 'form-control', :required => true

  .form-group.col-md-12
    .col-md-4.col-lg-3.text-right
      = f.label :password_confirmation
    .col-md-6.col-lg-7
      = f.password_field :password_confirmation, :class => 'form-control', :required => true


  .form-group.col-md-12
    .col-md-6.col-lg-7.col-md-offset-4.col-md-offset-3
      = f.submit 'Зарегистрироваться', :class => 'btn btn-primary'

app/views/users/new.html.slim
- if current_user
  h1
    | Вы вошли в систему под email:
    = current_user.email
-else
  = render 'new'