config/routes.rb
Rails.application.routes.draw do

  root :to => 'application#index'

  get 'logout' => 'sessions#destroy', :as => 'log_out'
  get 'login' => 'sessions#new', :as => 'log_in'
  post 'login' => 'sessions#create'
  get 'register' => 'users#new', :as => 'sign_up'
  post 'register' => 'users#create'

  get 'user_id' => 'application#user_id'
  get 'current_contact' => 'application#current_contact', :defaults => {format: :json}

  resources :users, :except => :new
  resources :sessions, :except => :new

  scope '/api' do
    resources :contacts, :defaults => {format: :json}

    resources :resource_types
    resources :partners

    resources :event_documents

    resources :events

    resources :finance_programs

    resources :currencies

    resources :finance_sources

    resources :projects, :defaults => {format: :json}

    resources :project_tasks, :defaults => {format: :json}

    resources :project_statuses, :defaults => {format: :json}

    resources :project_task_statuses, :defaults => {format: :json}

    resources :project_resources, :defaults => {format: :json}

    get 'resoursable' => 'resoursable#index', :defaults => {format: :json}

    resources :equips, :defaults => {format: :json}

    resources :equip_statuses, :defaults => {format: :json}

    resources :intellect_types

    resources :intellect_properties

    resources :socnet_links

    resources :socnets

    resources :theses

    resources :papers

    resources :degrees

    resources :ranks

    resources :scientists

    resources :rooms

    resources :subunits

    resources :specialties

    resources :faculties

    resources :universities

    resources :students

    resources :industries

    resources :workposts

    resources :skills, :defaults => {format: :json}

    resources :organizations

    resources :contact_data

    resources :links
  end

  mount RailsAdmin::Engine => '/adminpanel', :as => 'rails_admin'

  get '*path' => 'application#index'
end

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title EvaDB
    base href="/"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tag
  body
    nav.navbar.navbar-default style=("position:fixed; z-index:100;width: 100%;")
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed data-target="#bs-example-navbar-collapse-2" data-toggle="collapse" type="button"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="/"
            =image_tag "eva.png"
        .collapse.navbar-collapse
          ul.nav.navbar-nav
            -if current_user
              li
                a href="#" class="disabled"
                  =fa_icon 'info'
                  | &nbsp; О компании
              li
                a href="#" class="disabled"
                  =fa_icon 'line-chart'
                  | &nbsp; Управленческий учет
              li
                =link_to rails_admin_path, target: "_blank" do
                  =fa_icon 'database'
                  | &nbsp; База данных
              li
                a href="#" class="disabled"
                  =fa_icon 'skyatlas'
                  | &nbsp; Файлы
              li
                a href="#" class="disabled"
                  =fa_icon 'cogs'
                  | &nbsp; Настройки
            -else
              li.first.dropdown
                a href="/" title="Главная"
                  | Главная
            /li.last.dropdown
            /  a.dropdown-toggle aria-expanded="false" data-toggle="dropdown" href="#" role="button"
            /    | Связаться с нами
            /    span.caret
            /  ul.dropdown-menu
            /    li.first
            /      a href="http://rize.su/l/connect/gruppa-v-vk" title=("Группа в ВК")  Группа в ВК
            /    li.last
            /      a href="http://rize.su/l/connect/contacts" title="Контакты"  Контакты
          ul.nav.navbar-nav.navbar-right
            -if current_user
              /li
              /  =link_to "Личный кабинет #{current_user.email}", cabinet_path
              li
                =link_to 'Выйти', log_out_path
            -else
              li
                =link_to 'Зарегистрироваться', sign_up_path
              li
                =link_to 'Войти', log_in_path
    /ng-strict-di=''
    div class="container" style="padding-top: 80px"
      = yield